/* Challengers Player Analytics — static/offline dashboard. */
(() => {
  'use strict';

  // ── Data helpers ────────────────────────────────────────────────────────
  const DATA = Array.isArray(window.PLAYER_DATA) ? window.PLAYER_DATA : [];
  const METRICS = [
    ['K/D', 'K/D'], ['BP Rating', 'BP Rating'], ['Slayer Rating', 'Slayer Rating'], ['T.E.S', 'T.E.S'], ['NTK%', 'NTK%'],
    ['HP K/D', 'HP K/D'], ['HP DMG/10m', 'HP DMG/10m'], ['HP Time/10m', 'HP Time/10m'], ['HP ENG/10m', 'HP ENG/10m'],
    ['SND K/D', 'SND K/D'], ['SND ADR', 'SND ADR'], ['SND KpR', 'SND KpR'], ['CTL KD', 'CTL KD'], ['CTL DMG/10M', 'CTL DMG/10M']
  ];
  const metricLabel = Object.fromEntries(METRICS);
  const byName = new Map(DATA.map(p => [p.Player, p]));
  const charts = {};
  const $ = id => document.getElementById(id);
  const value = (p, key) => Number.isFinite(Number(p?.[key])) ? Number(p[key]) : null;
  const valid = (items, key) => items.map(p => value(p, key)).filter(v => v !== null);
  const mean = nums => nums.length ? nums.reduce((a, b) => a + b, 0) / nums.length : null;
  const median = nums => { const a = [...nums].sort((x,y) => x-y); return a.length ? (a[Math.floor((a.length-1)/2)] + a[Math.ceil((a.length-1)/2)]) / 2 : null; };
  const min = nums => nums.length ? Math.min(...nums) : null;
  const max = nums => nums.length ? Math.max(...nums) : null;
  // Percentile rank is the share of valid field values at or below this value.
  const percentileRank = (items, key, v) => { const vals = valid(items, key); return v === null || !vals.length ? null : 100 * vals.filter(x => x <= v).length / vals.length; };
  const percentileThreshold = (items, key, p) => { const vals = valid(items, key).sort((a,b) => a-b); if (!vals.length) return null; return vals[Math.max(0, Math.min(vals.length-1, Math.ceil((p / 100) * vals.length) - 1))]; };
  const averagePercentile = vals => { const present = vals.filter(v => v !== null); return present.length ? mean(present) : null; };
  const fmt = (v, key = '') => { if (v === null || v === undefined || Number.isNaN(v)) return '—'; if (key.includes('%') || key === 'NTK%') return `${Number(v).toFixed(1)}%`; if (/Kills|Deaths|Maps|Series|Plants|Defuses|Clutches|Ticks|Won|Lost/.test(key)) return Math.round(v).toLocaleString(); if (/Rating|ADR|DMG|Time|ENG|K\/10|D\/10|A\/10|KpR|DpR|ApR|T\.E\.S|K\/D|KD/.test(key)) return Number(v).toFixed(2); return Number(v).toFixed(2); };
  const clamp = (x,a,b) => Math.max(a,Math.min(b,x));
  const smartRange = vals => { let lo=min(vals), hi=max(vals); if (lo === null) return [0,1]; const span=hi-lo || Math.abs(hi) * .2 || 1; return [lo-span*.1,hi+span*.12]; };
  const pctText = p => { if (p === null) return '—'; const n=Math.round(p), mod100=n%100, suffix=mod100>=11&&mod100<=13?'th':n%10===1?'st':n%10===2?'nd':n%10===3?'rd':'th'; return `${n}${suffix} percentile`; };

  // ── State and filter handling ───────────────────────────────────────────
  const state = {
    query: '', mode: 'overall', minSeries: 0, minHp: 0, minSnd: 0, minCtl: 0,
    scatterX: 'K/D', scatterY: 'BP Rating', rankMetric: 'BP Rating', rankLimit: 10,
    quadrantPreset: 'overall', quadrantX: 'K/D', quadrantY: 'BP Rating', distributionMetric: 'BP Rating',
    tableSort: 'Rank', tableAsc: true, modeColumns: false, selected: null, compare: null, detailTab: 'overall'
  };
  const filtered = () => DATA.filter(p => {
    const q = state.query.trim().toLowerCase();
    return (!q || p.Player.toLowerCase().includes(q)) &&
      (value(p,'Series Played') ?? 0) >= state.minSeries && (value(p,'HP Maps Played') ?? 0) >= state.minHp &&
      (value(p,'SND Maps Played') ?? 0) >= state.minSnd && (value(p,'CTL Maps') ?? 0) >= state.minCtl;
  });
  function selectionField() { return filtered().length ? filtered() : DATA; }
  function readHash() { const m = decodeURIComponent(location.hash.replace(/^#/, '')).match(/(?:^|&)player=([^&]+)/); if (m && byName.has(m[1])) state.selected = m[1]; }
  function updateHash() { if (state.selected) history.replaceState(null, '', `#player=${encodeURIComponent(state.selected)}`); else history.replaceState(null, '', location.pathname + location.search); }
  function updateFilterStatus() { $('visibleCount').textContent = filtered().length; $('totalCount').textContent = DATA.length; }

  // ── General UI construction ─────────────────────────────────────────────
  function populateMetricSelect(id, current) {
    const el = $(id); el.innerHTML = METRICS.map(([k,l]) => `<option value="${k}">${l}</option>`).join(''); el.value = current;
  }
  function initSelectors() { ['scatterX','scatterY','rankingMetric','quadrantX','quadrantY','distributionMetric'].forEach(id => populateMetricSelect(id, state[{scatterX:'scatterX',scatterY:'scatterY',rankingMetric:'rankMetric',quadrantX:'quadrantX',quadrantY:'quadrantY',distributionMetric:'distributionMetric'}[id]])); }
  function renderKpis() {
    const field = selectionField();
    const cards = [['Total Players', null], ['Highest BP Rating', 'BP Rating'], ['Highest K/D', 'K/D'], ['Highest Slayer Rating', 'Slayer Rating'], ['Highest SND K/D', 'SND K/D']];
    $('kpiGrid').innerHTML = cards.map(([label, metric]) => {
      if (metric === null) return `<article class="kpi"><div class="kpi-label">${label}</div><div class="kpi-value">${field.length}</div><div class="kpi-player">Filtered field</div></article>`;
      const player = [...field].filter(p => value(p,metric) !== null).sort((a,b) => value(b,metric)-value(a,metric))[0];
      return `<article class="kpi" data-player="${player?.Player || ''}"><div class="kpi-label">${label}</div><div class="kpi-value">${fmt(value(player,metric),metric)}</div><div class="kpi-player">${player?.Player || 'No data'}</div></article>`;
    }).join('');
    $('kpiGrid').querySelectorAll('[data-player]').forEach(c => c.addEventListener('click', () => openPlayer(c.dataset.player)));
  }
  function tooltip(params) { const p = params.data?.player || params.data?.[3]; if (!p) return ''; return `<div class="tip"><strong style="font-size:15px">${p.Player}</strong><br><span style="color:#a9a69e">Rank #${p.Rank} · ${fmt(value(p,'Series Played'),'Series Played')} series</span><hr style="border:0;border-top:1px solid #5f491b;margin:7px 0"><div>K/D <b>${fmt(value(p,'K/D'),'K/D')}</b> &nbsp; BP <b>${fmt(value(p,'BP Rating'),'BP Rating')}</b></div><div>Slayer <b>${fmt(value(p,'Slayer Rating'),'Slayer Rating')}</b> &nbsp; SND K/D <b>${fmt(value(p,'SND K/D'),'SND K/D')}</b></div><small style="color:#d5a43b">Click for profile</small></div>`; }
  function initChart(id) { if (!charts[id]) charts[id] = echarts.init($(id), null, {renderer:'canvas'}); return charts[id]; }
  const selectedStyle = p => p.Player === state.selected ? {borderColor:'#fff8e8',borderWidth:2,shadowBlur:13,shadowColor:'#d5a43b'} : {};
  function pointData(players,x,y) { return players.filter(p => value(p,x)!==null && value(p,y)!==null).map(p => ({value:[value(p,x),value(p,y)],player:p,symbolSize:clamp(7 + Math.sqrt(value(p,'Series Played')||0)*1.8,8,17),itemStyle:{color:p.Player===state.selected?'#d5a43b':'#d2d0ca',opacity:p.Player===state.selected?1:.76,...selectedStyle(p)}})); }

  // ── Main visualizations ──────────────────────────────────────────────────
  function scatterOption(players, x, y, labels) {
    const xVals=valid(players,x), yVals=valid(players,y), xAvg=mean(xVals), yAvg=mean(yVals), [xLo,xHi]=smartRange(xVals),[yLo,yHi]=smartRange(yVals);
    return {animationDuration:280,grid:{left:58,right:24,top:26,bottom:54},tooltip:{trigger:'item',backgroundColor:'#100f0d',borderColor:'#74571c',textStyle:{color:'#f7f4eb'},formatter:tooltip},xAxis:{type:'value',name:metricLabel[x],nameLocation:'middle',nameGap:35,min:xLo,max:xHi,splitLine:{lineStyle:{color:'rgba(213,164,59,.1)'}},axisLabel:{color:'#a9a69e'},nameTextStyle:{color:'#a9a69e',fontWeight:700}},yAxis:{type:'value',name:metricLabel[y],nameLocation:'middle',nameGap:42,min:yLo,max:yHi,splitLine:{lineStyle:{color:'rgba(213,164,59,.1)'}},axisLabel:{color:'#a9a69e'},nameTextStyle:{color:'#a9a69e',fontWeight:700}},series:[{type:'scatter',data:pointData(players,x,y),emphasis:{scale:1.3,label:{show:true,formatter:p=>p.data.player.Player,position:'top',color:'#fff',fontWeight:800}},markLine:{silent:true,symbol:'none',lineStyle:{color:'rgba(213,164,59,.62)',type:'dashed'},label:{show:false},data:[{xAxis:xAvg},{yAxis:yAvg}]},markArea:labels?{silent:true,itemStyle:{color:'rgba(213,164,59,.03)'},label:{show:true,color:'rgba(213,164,59,.36)',fontWeight:700,fontSize:11},data:[[{name:'HIGH IMPACT',xAxis:xAvg,yAxis:yAvg},{xAxis:xHi,yAxis:yHi}],[{name:'EFFICIENCY UPSIDE',xAxis:xAvg,yAxis:yLo},{xAxis:xHi,yAxis:yAvg}],[{name:'IMPACT OVER EFFICIENCY',xAxis:xLo,yAxis:yAvg},{xAxis:xAvg,yAxis:yHi}]]}:undefined}]};
  }
  function renderPlayerMap() { const c=initChart('playerMap'); c.setOption(scatterOption(filtered(),state.scatterX,state.scatterY,true),true); c.off('click');c.on('click',p=>p.data?.player&&openPlayer(p.data.player.Player)); }
  function renderRanking() { const field=[...filtered()].filter(p=>value(p,state.rankMetric)!==null).sort((a,b)=>value(b,state.rankMetric)-value(a,state.rankMetric)); const rows=state.rankLimit==='all'?field:field.slice(0,state.rankLimit); const height=Math.max(300,Math.min(850,rows.length*27+60)); $('rankingChart').style.height=`${height}px`; const c=initChart('rankingChart'); c.resize(); c.setOption({animationDuration:280,grid:{left:105,right:34,top:14,bottom:20},tooltip:{trigger:'axis',axisPointer:{type:'shadow'},backgroundColor:'#100f0d',borderColor:'#74571c',formatter:p=>tooltip({data:{player:rows[p[0].dataIndex]}})},xAxis:{type:'value',splitLine:{lineStyle:{color:'rgba(213,164,59,.1)'}},axisLabel:{color:'#a9a69e'}},yAxis:{type:'category',inverse:true,data:rows.map(p=>p.Player),axisLabel:{color:'#e4ded2',fontWeight:700},axisTick:{show:false},axisLine:{show:false}},series:[{type:'bar',data:rows.map(p=>({value:value(p,state.rankMetric),itemStyle:{color:p.Player===state.selected?'#d5a43b':'#8c6b28',borderRadius:[0,4,4,0]}})),barMaxWidth:16,label:{show:true,position:'right',color:'#c7c1b3',formatter:p=>fmt(p.value,state.rankMetric)} }]},true); c.off('click');c.on('click',p=>rows[p.dataIndex]&&openPlayer(rows[p.dataIndex].Player)); }
  function renderQuadrant() { const c=initChart('quadrantChart');c.setOption(scatterOption(filtered(),state.quadrantX,state.quadrantY,false),true);c.off('click');c.on('click',p=>p.data?.player&&openPlayer(p.data.player.Player)); }
  function renderDistribution() { const field=selectionField(), metric=state.distributionMetric, selected=state.selected?byName.get(state.selected):null; const sorted=[...field].filter(p=>value(p,metric)!==null).sort((a,b)=>value(a,metric)-value(b,metric)); const vals=sorted.map(p=>value(p,metric)); const selectedIndex=selected?sorted.findIndex(p=>p.Player===selected.Player):-1; const c=initChart('distributionChart'); c.setOption({animationDuration:250,grid:{left:52,right:20,top:40,bottom:38},tooltip:{trigger:'item',backgroundColor:'#100f0d',borderColor:'#74571c',formatter:tooltip},xAxis:{type:'value',name:metricLabel[metric],nameLocation:'middle',nameGap:26,min:smartRange(vals)[0],max:smartRange(vals)[1],splitLine:{lineStyle:{color:'rgba(213,164,59,.1)'}},axisLabel:{color:'#a9a69e'}},yAxis:{show:false,min:0,max:1},graphic:selectedIndex>=0?[{type:'text',left:'center',top:8,style:{text:`${selected.Player}: ${fmt(value(selected,metric),metric)} · ${pctText(percentileRank(field,metric,value(selected,metric)))}`,fill:'#d5a43b',font:'700 12px sans-serif'}}]:[{type:'text',left:'center',top:8,style:{text:'Select a player to highlight their position',fill:'#a9a69e',font:'12px sans-serif'}}],series:[{type:'scatter',data:sorted.map((p,i)=>({value:[value(p,metric),.5+(i%5-2)*.052],player:p,symbolSize:p.Player===state.selected?17:7,itemStyle:{color:p.Player===state.selected?'#f0c56a':'#817c70',opacity:p.Player===state.selected?1:.6,...selectedStyle(p)}})),emphasis:{label:{show:true,formatter:p=>p.data.player.Player,position:'top',color:'#fff'}}},{type:'line',silent:true,data:[[percentileThreshold(field,metric,25),.1],[percentileThreshold(field,metric,25),.9]],symbol:'none',lineStyle:{color:'rgba(213,164,59,.32)',type:'dashed'}},{type:'line',silent:true,data:[[percentileThreshold(field,metric,75),.1],[percentileThreshold(field,metric,75),.9]],symbol:'none',lineStyle:{color:'rgba(240,197,106,.65)',type:'dashed'}}]},true); c.off('click');c.on('click',p=>p.data?.player&&openPlayer(p.data.player.Player)); $('distributionHint').textContent=selected?`${selected.Player} is highlighted against the filtered field.`:'Select a player to locate them in the field.'; }

  // ── Table ────────────────────────────────────────────────────────────────
  const overallColumns=[['Rank','Rank'],['Player','Player'],['K/D','K/D'],['BP Rating','BP Rating'],['Slayer Rating','Slayer Rating'],['T.E.S','T.E.S'],['NTK%','NTK%'],['HP K/D','HP K/D'],['SND K/D','SND K/D'],['CTL KD','CTL KD']];
  const modeColumns=[['Rank','Rank'],['Player','Player'],['HP K/10m','HP K/10m'],['HP DMG/10m','HP DMG/10m'],['HP Time/10m','HP Time/10m'],['SND ADR','SND ADR'],['SND KpR','SND KpR'],['SND OpD W%','SND OpD W%'],['CTL K/10M','CTL K/10M'],['CTL DMG/10M','CTL DMG/10M']];
  function renderTable() { const cols=state.modeColumns?modeColumns:overallColumns; let rows=[...filtered()]; const key=state.tableSort; rows.sort((a,b)=> {const av=key==='Player'?a.Player:value(a,key),bv=key==='Player'?b.Player:value(b,key);const d=typeof av==='string'?av.localeCompare(bv):(av??-Infinity)-(bv??-Infinity);return state.tableAsc?d:-d;}); $('playerTable').querySelector('thead').innerHTML=`<tr>${cols.map(([k,l])=>`<th data-key="${k}">${l}${state.tableSort===k?(state.tableAsc?' ↑':' ↓'):''}</th>`).join('')}</tr>`; $('playerTable').querySelector('tbody').innerHTML=rows.map(p=>`<tr class="${p.Player===state.selected?'selected':''}" data-player="${p.Player}">${cols.map(([k])=>k==='Rank'?`<td><span class="rank-badge ${p.Rank<=10?'rank-top':''}">${p.Rank}</span></td>`:k==='Player'?`<td class="player-cell">${p.Player}</td>`:`<td class="${percentileRank(selectionField(),k,value(p,k))>=90?'accent':''}">${fmt(value(p,k),k)}</td>`).join('')}</tr>`).join(''); $('playerTable').querySelectorAll('th').forEach(th=>th.addEventListener('click',()=>{const k=th.dataset.key; state.tableAsc=state.tableSort===k?!state.tableAsc:k==='Rank';state.tableSort=k;renderTable();})); $('playerTable').querySelectorAll('tbody tr').forEach(tr=>tr.addEventListener('click',()=>openPlayer(tr.dataset.player))); }

  // ── Player detail calculations ──────────────────────────────────────────
  /* Radar axes use percentiles, never raw stats. Composite axes are unweighted
     averages of component percentile ranks: overall BP; slaying K/D + Slayer;
     HP HP K/D + damage + engagements; SND SND K/D + ADR + KpR; Control KD +
     damage + engagements; efficiency T.E.S + NTK%. These are dashboard-derived,
     not official BreakingPoint ratings. */
  const radarDefinitions=[['Overall Rating',['BP Rating']],['Slaying',['K/D','Slayer Rating']],['Hardpoint',['HP K/D','HP DMG/10m','HP ENG/10m']],['Search & Destroy',['SND K/D','SND ADR','SND KpR']],['Control',['CTL KD','CTL DMG/10M','CTL Eng/10M']],['Efficiency',['T.E.S','NTK%']]];
  function radarScores(p, field) { return radarDefinitions.map(([,keys])=>averagePercentile(keys.map(k=>percentileRank(field,k,value(p,k))))); }
  const compareMetrics=['K/D','BP Rating','Slayer Rating','HP K/D','SND K/D','CTL KD'];
  const modeMetricMap={hp:['HP K/D','HP K/10m','HP D/10m','HP A/10m','HP DMG/10m','HP Time/10m','HP ENG/10m','HP NTK%'],snd:['SND K/D','SND KpR','SND DpR','SND ApR','SND ADR','SND OpD W%','SND NTK%'],ctl:['CTL KD','CTL K/10M','CTL DMG/10M','CTL Eng/10M','CTL Ticks']};
  function badges(p,field) { const b=[];if((p.Rank||999)<=10)b.push('Top 10 Overall');if(averagePercentile(['K/D','Slayer Rating'].map(k=>percentileRank(field,k,value(p,k))))>=85)b.push('Elite Slayer');if(averagePercentile(['SND K/D','SND ADR','SND KpR'].map(k=>percentileRank(field,k,value(p,k))))>=80)b.push('Strong SND');if(averagePercentile(['HP K/D','HP DMG/10m','HP ENG/10m'].map(k=>percentileRank(field,k,value(p,k))))>=80)b.push('Strong Hardpoint');return b; }
  // Final dataset scouting note: each sentence is derived from the player's
  // actual percentile profile and mode sample sizes, rather than invented copy.
  function scoutSummary(p) {
    const field = DATA;
    const score = keys => averagePercentile(keys.map(k => percentileRank(field,k,value(p,k))));
    const modes = [
      {name:'Hardpoint',score:score(['HP K/D','HP DMG/10m','HP ENG/10m']),metrics:['HP K/D','HP DMG/10m'],sample:value(p,'HP Maps Played'),sampleLabel:'maps'},
      {name:'Search & Destroy',score:score(['SND K/D','SND ADR','SND KpR']),metrics:['SND K/D','SND ADR'],sample:value(p,'SND Maps Played'),sampleLabel:'maps'},
      {name:'Control',score:score(['CTL KD','CTL DMG/10M','CTL Eng/10M']),metrics:['CTL KD','CTL DMG/10M'],sample:value(p,'CTL Maps'),sampleLabel:'maps'}
    ].filter(m => m.score !== null);
    const overall = percentileRank(field,'BP Rating',value(p,'BP Rating'));
    const kd = percentileRank(field,'K/D',value(p,'K/D'));
    const tier = overall >= 90 ? 'elite' : overall >= 75 ? 'high-end' : overall >= 55 ? 'above-average' : overall >= 40 ? 'middle-of-the-field' : 'developing';
    const strongest = [...modes].sort((a,b) => b.score-a.score)[0];
    const softest = [...modes].sort((a,b) => a.score-b.score)[0];
    const modeDetail = m => `${fmt(value(p,m.metrics[0]),m.metrics[0])} ${m.metrics[0]} (${pctText(percentileRank(field,m.metrics[0],value(p,m.metrics[0])))}), plus ${fmt(value(p,m.metrics[1]),m.metrics[1])} ${m.metrics[1]} (${pctText(percentileRank(field,m.metrics[1],value(p,m.metrics[1])))})`;
    const sampleNote = (value(p,'Series Played') || 0) <= 5 || (softest?.sample || 0) <= 5 ? ` The available sample is ${fmt(value(p,'Series Played'),'Series Played')} series, so the smaller mode splits deserve added context.` : '';
    if (!strongest || !softest) return `${p.Player} is ranked #${p.Rank} overall with a ${fmt(value(p,'BP Rating'),'BP Rating')} BP Rating and ${fmt(value(p,'K/D'),'K/D')} K/D.`;
    const review = softest.name === strongest.name ? `The profile is notably balanced across all three modes.` : softest.score < 45 ? `${softest.name} is the clearest review point at a ${pctText(softest.score)} composite, making it the most useful area for film review.` : `${softest.name} is comparatively less dominant (${pctText(softest.score)} composite), but remains a workable part of the overall profile.`;
    return `${p.Player} is an ${tier} overall profile, ranked #${p.Rank} with a ${fmt(value(p,'BP Rating'),'BP Rating')} BP Rating (${pctText(overall)}) and ${fmt(value(p,'K/D'),'K/D')} K/D (${pctText(kd)}). The clearest strength is ${strongest.name} (${pctText(strongest.score)} composite), led by ${modeDetail(strongest)} across ${fmt(strongest.sample,'Maps')} ${strongest.sampleLabel}. ${review}${sampleNote}`;
  }
  function profileMarkup(p,field) { const bp=badges(p,field); const summary=scoutSummary(p); const compareOptions=DATA.filter(x=>x.Player!==p.Player).map(x=>`<option value="${x.Player}" ${x.Player===state.compare?'selected':''}>${x.Player}</option>`).join('');return `<div class="drawer-content"><button id="closeDrawer" class="drawer-close" type="button" aria-label="Close profile">×</button><header class="profile-head"><span class="eyebrow">PLAYER SCOUTING PROFILE</span><h2 class="profile-name">${p.Player}</h2><div class="profile-meta"><span>Overall rank <strong>#${p.Rank}</strong></span><span>•</span><span>${fmt(value(p,'Series Played'),'Series Played')} series played</span><span>•</span><span>HP ${fmt(value(p,'HP Maps Played'),'HP Maps Played')} / SND ${fmt(value(p,'SND Maps Played'),'SND Maps Played')} / CTL ${fmt(value(p,'CTL Maps'),'CTL Maps')} maps</span></div>${bp.length?`<div class="badges">${bp.map(x=>`<span class="badge">${x}</span>`).join('')}</div>`:''}</header><section class="scout-summary"><span class="eyebrow">BUSHAI SUMMARY</span><p>${summary}</p></section><div class="profile-kpis"><div class="profile-kpi"><span>BP Rating</span><strong>${fmt(value(p,'BP Rating'),'BP Rating')}</strong></div><div class="profile-kpi"><span>K/D</span><strong>${fmt(value(p,'K/D'),'K/D')}</strong></div><div class="profile-kpi"><span>Kills</span><strong>${fmt(value(p,'Kills'),'Kills')}</strong></div><div class="profile-kpi"><span>Deaths</span><strong>${fmt(value(p,'Deaths'),'Deaths')}</strong></div></div><div class="comparison-select"><label for="comparePlayer">Compare with</label><select id="comparePlayer"><option value="">No comparison</option>${compareOptions}</select>${state.compare?'<button id="clearCompare" type="button">Clear</button>':''}</div><nav class="detail-tabs" aria-label="Player profile sections">${[['overall','Overall'],['hp','Hardpoint'],['snd','Search & Destroy'],['ctl','Control']].map(([k,l])=>`<button data-tab="${k}" class="${state.detailTab===k?'active':''}" type="button">${l}</button>`).join('')}</nav><section id="detailVisuals"></section></div>`; }
  function renderDetailVisuals(p,field) { const target=$('detailVisuals'), rival=state.compare?byName.get(state.compare):null; if(state.detailTab==='overall') { const cards=['BP Rating','K/D','HP K/D','HP DMG/10m','SND K/D','SND ADR','CTL KD']; target.innerHTML=`<div class="detail-section"><h3>Relative Performance Profile</h3><p class="detail-note">Dataset percentiles and composite axes are independently calculated from source statistics; they are not official Breaking Point metrics.</p><div id="radarChart" class="detail-chart"></div></div><div class="detail-section"><h3>Player vs field</h3><p class="detail-note">Dataset percentile comparison: field average is 50th; top-quartile threshold is 75th.</p><div id="fieldCompareChart" class="detail-chart small"></div></div><div class="percentile-grid">${cards.map(k=>`<div class="percentile-card"><span>${k}</span><strong>${fmt(value(p,k),k)}</strong><b>${pctText(percentileRank(field,k,value(p,k)))}</b></div>`).join('')}</div>`; renderRadar(p,rival,field);renderFieldCompare(p,rival,field); } else { const keys=modeMetricMap[state.detailTab]; target.innerHTML=`<div class="detail-section"><h3>${state.detailTab==='hp'?'Hardpoint':state.detailTab==='snd'?'Search & Destroy':'Control'} breakdown</h3><p class="detail-note">Dataset percentile context is independently calculated; map counts remain visible to help interpret sample size.</p><div id="modeCompareChart" class="detail-chart"></div><div class="mode-cards">${keys.map(k=>`<div class="mode-stat"><span>${k}</span><strong>${fmt(value(p,k),k)}</strong><small>${pctText(percentileRank(field,k,value(p,k)))}</small></div>`).join('')}</div></div>`;renderModeCompare(p,rival,field,keys); } }
  function renderRadar(p,rival,field) { const c=echarts.init($('radarChart'));charts.radar=c;const names=radarDefinitions.map(x=>x[0]);const data=[{value:radarScores(p,field),name:p.Player,areaStyle:{color:'rgba(213,164,59,.2)'},lineStyle:{color:'#d5a43b'},itemStyle:{color:'#f0c56a'}}];if(rival)data.push({value:radarScores(rival,field),name:rival.Player,areaStyle:{color:'rgba(213,211,204,.1)'},lineStyle:{color:'#d5d3cc'},itemStyle:{color:'#d5d3cc'}});c.setOption({tooltip:{},legend:rival?{top:0,textStyle:{color:'#dedbd2'},itemWidth:12,itemHeight:8}:undefined,radar:{center:['50%',rival?'56%':'53%'],radius:'65%',indicator:names.map(name=>({name,max:100})),splitArea:{areaStyle:{color:['rgba(255,255,255,.02)','rgba(255,255,255,.04)']}},axisName:{color:'#d6d0c2',fontSize:10},splitLine:{lineStyle:{color:'rgba(213,164,59,.23)'}},axisLine:{lineStyle:{color:'rgba(213,164,59,.23)'}}},series:[{type:'radar',data}]}); }
  function renderFieldCompare(p,rival,field) { const c=echarts.init($('fieldCompareChart'));charts.fieldCompare=c;const score=(person,k)=>percentileRank(field,k,value(person,k));const series=[{name:p.Player,type:'bar',data:compareMetrics.map(k=>score(p,k)),itemStyle:{color:'#d5a43b',borderRadius:[3,3,0,0]}}];if(rival)series.push({name:rival.Player,type:'bar',data:compareMetrics.map(k=>score(rival,k)),itemStyle:{color:'#d5d3cc',borderRadius:[3,3,0,0]}});series.push({name:'Field avg',type:'bar',data:compareMetrics.map(()=>50),itemStyle:{color:'#77736c',borderRadius:[3,3,0,0]}});series.push({name:'Top 25%',type:'bar',data:compareMetrics.map(()=>75),itemStyle:{color:'#f0c56a',borderRadius:[3,3,0,0]}});c.setOption({animationDuration:220,tooltip:{trigger:'axis',valueFormatter:v=>`${Math.round(v)}th percentile`},legend:{top:0,textStyle:{color:'#d6d0c2'},itemWidth:10,itemHeight:8},grid:{left:42,right:14,top:36,bottom:45},xAxis:{type:'category',data:compareMetrics,axisLabel:{color:'#c4bdad',fontSize:10,rotate:24}},yAxis:{type:'value',min:0,max:100,splitLine:{lineStyle:{color:'rgba(213,164,59,.1)'}},axisLabel:{color:'#a9a69e',formatter:'{value}%'}},series}); }
  function renderModeCompare(p,rival,field,keys) { const c=echarts.init($('modeCompareChart'));charts.modeCompare=c;const data=[{name:p.Player,value:keys.map(k=>percentileRank(field,k,value(p,k)))}];if(rival)data.push({name:rival.Player,value:keys.map(k=>percentileRank(field,k,value(rival,k)))});c.setOption({tooltip:{trigger:'axis'},legend:rival?{top:0,textStyle:{color:'#dedbd2'}}:undefined,radar:{center:['50%',rival?'57%':'52%'],radius:'68%',indicator:keys.map(k=>({name:k,max:100})),axisName:{color:'#d6d0c2',fontSize:9},splitArea:{areaStyle:{color:['rgba(255,255,255,.02)','rgba(255,255,255,.04)']}},splitLine:{lineStyle:{color:'rgba(213,164,59,.23)'}},axisLine:{lineStyle:{color:'rgba(213,164,59,.23)'}}},series:[{type:'radar',data:data.map((d,i)=>({...d,areaStyle:{color:i?'rgba(213,211,204,.1)':'rgba(213,164,59,.2)'},lineStyle:{color:i?'#d5d3cc':'#d5a43b'},itemStyle:{color:i?'#d5d3cc':'#f0c56a'}}))}]}); }
  function openPlayer(name) { const p=byName.get(name);if(!p)return;state.selected=name;if(state.compare===name)state.compare=null;state.detailTab='overall';updateHash();$('drawerContent').innerHTML=profileMarkup(p,selectionField());$('playerDrawer').classList.add('open');$('playerDrawer').setAttribute('aria-hidden','false');$('drawerScrim').hidden=false;requestAnimationFrame(()=>renderDetailVisuals(p,selectionField()));bindDetailEvents();renderAll(); }
  function closePlayer() { state.selected=null;state.compare=null;updateHash();$('playerDrawer').classList.remove('open');$('playerDrawer').setAttribute('aria-hidden','true');$('drawerScrim').hidden=true;renderAll(); }
  function bindDetailEvents() { const p=byName.get(state.selected);$('closeDrawer').addEventListener('click',closePlayer);$('comparePlayer').addEventListener('change',e=>{state.compare=e.target.value||null;$('drawerContent').innerHTML=profileMarkup(p,selectionField());requestAnimationFrame(()=>{renderDetailVisuals(p,selectionField());bindDetailEvents();});});$('clearCompare')?.addEventListener('click',()=>{state.compare=null;$('drawerContent').innerHTML=profileMarkup(p,selectionField());requestAnimationFrame(()=>{renderDetailVisuals(p,selectionField());bindDetailEvents();});});document.querySelectorAll('.detail-tabs button').forEach(b=>b.addEventListener('click',()=>{state.detailTab=b.dataset.tab;document.querySelectorAll('.detail-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderDetailVisuals(p,selectionField());})); }

  // ── Events and initialization ───────────────────────────────────────────
  function renderAll() { updateFilterStatus();renderKpis();renderPlayerMap();renderRanking();renderQuadrant();renderDistribution();renderTable(); }
  function bindEvents() {
    $('playerSearch').addEventListener('input',e=>{state.query=e.target.value;renderAll();});
    $('modeFocus').addEventListener('input',e=>{state.mode=e.target.value;const focus={overall:['K/D','BP Rating'],hp:['HP K/D','HP DMG/10m'],snd:['SND K/D','SND ADR'],ctl:['CTL KD','CTL DMG/10M']}[state.mode];state.scatterX=focus[0];state.scatterY=focus[1];$('scatterX').value=focus[0];$('scatterY').value=focus[1];renderAll();});
    [['minSeries','minSeries'],['minHpMaps','minHp'],['minSndMaps','minSnd'],['minCtlMaps','minCtl']].forEach(([id,key])=>$(id).addEventListener('input',e=>{state[key]=Math.max(0,Number(e.target.value)||0);renderAll();}));
    [['scatterX','scatterX'],['scatterY','scatterY'],['rankingMetric','rankMetric'],['quadrantX','quadrantX'],['quadrantY','quadrantY'],['distributionMetric','distributionMetric']].forEach(([id,key])=>$(id).addEventListener('change',e=>{state[key]=e.target.value;renderAll();}));
    $('rankLimit').addEventListener('click',e=>{if(e.target.dataset.limit){state.rankLimit=e.target.dataset.limit==='all'?'all':Number(e.target.dataset.limit);$('rankLimit').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===e.target));renderRanking();}});
    $('quadrantPreset').addEventListener('change',e=>{state.quadrantPreset=e.target.value;const p={overall:['K/D','BP Rating'],objective:['Slayer Rating','HP Time/10m'],snd:['SND K/D','SND ADR'],ctl:['CTL KD','CTL DMG/10M']}[e.target.value];if(p){state.quadrantX=p[0];state.quadrantY=p[1];$('quadrantX').value=p[0];$('quadrantY').value=p[1];}renderQuadrant();});
    $('tableMode').addEventListener('click',e=>{const button=e.target.closest('[data-table-view]');if(!button)return;state.modeColumns=button.dataset.tableView==='modes';$('tableMode').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===button));renderTable();});
    $('resetFilters').addEventListener('click',()=>{Object.assign(state,{query:'',mode:'overall',minSeries:0,minHp:0,minSnd:0,minCtl:0});$('playerSearch').value='';$('modeFocus').value='overall';['minSeries','minHpMaps','minSndMaps','minCtlMaps'].forEach(id=>$(id).value=0);renderAll();});
    const openAbout=()=>{$('aboutModal').classList.add('open');$('aboutModal').setAttribute('aria-hidden','false');$('aboutScrim').hidden=false;$('aboutClose').focus();};const closeAbout=()=>{$('aboutModal').classList.remove('open');$('aboutModal').setAttribute('aria-hidden','true');$('aboutScrim').hidden=true;$('aboutButton').focus();};$('aboutButton').addEventListener('click',openAbout);$('aboutClose').addEventListener('click',closeAbout);$('aboutScrim').addEventListener('click',closeAbout);
    $('drawerScrim').addEventListener('click',closePlayer);document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('aboutScrim').hidden)closeAbout();else if(state.selected)closePlayer();}});window.addEventListener('resize',()=>Object.values(charts).forEach(c=>c?.resize()));
  }
  function init() { if(!DATA.length){document.body.innerHTML='<p style="padding:2rem;color:white">Player data could not be loaded.</p>';return;}readHash();initSelectors();bindEvents();renderAll();if(state.selected)openPlayer(state.selected);console.info(`Challengers Player Analytics: ${DATA.length} records loaded.`,Object.keys(DATA[0])); }
  init();
})();
